# Generated by Django 4.1.7 on 2023-04-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
